### ISSUE TITLE
matcap_uv doesn't account for perspective, I fixed it.

### ISSUE THREAD

**Issue by ConstaChugga** [bnpr/Malt#42]
I'm unsure as to the proper way to give fix submissions/submit code (if at all), apologies.

Fixed function (found in `Malt/Shaders/Common/Transform.glsl`):
```glsl
vec2 matcap_uv(vec3 normal)
{
	vec3 view_normal   = transform_normal(CAMERA, normal);
	vec3 view_incoming = transform_normal(CAMERA, view_direction());

	view_incoming.z += 1.;

	/// NOTE:
	/// If UV is kept as a vec3 rather than a vec2, the
	/// math done to the Z component provides the view dot norm
	/// product (not a straight gradient like X and Y though, Z is a sphere).
	/// I imagine some chrome effects will want to use that
	/// facing value, but not including it doesn't do harm.
	vec2 uv = view_incoming.xy * dot(view_normal, view_incoming);
	
	uv /= view_incoming.zz;
	uv -= view_normal;

	return 0.5 + -0.5 * uv.xy;
}
```

I imagine my code here can be simplified further, but I wrote this as a quick translation from my cycles shader nodes so compactness was not my goal.

Issue visualized:
Matcap_uv without fix in perspective (provides bogus mapping near the edges of the screen, especially on flat planes):
![image](https://user-images.githubusercontent.com/22027276/104806500-2e17fe00-5795-11eb-9cdf-984fb88e02e5.png)

With fix:
![image](https://user-images.githubusercontent.com/22027276/104806511-425bfb00-5795-11eb-9e86-6df47f295c61.png)

**Comment by pragma37** [comment]
> I'm unsure as to the proper way to give fix submissions/submit code (if at all)
Ideally you submit a pull request, so you get credited in the git history.

Regarding the issue itself, I think that's (at least theorically) the correct behaviour.
Matcaps map the surface based on its screen space normal, so coplanar surfaces get mapped to the same pixel. This is specially obvious in orthographic view, where flat planes map to flat colors.

May I ask where the math from your code comes from?

I took a look at [how the workbench engine does matcaps](https://github.com/blender/blender/blob/594f47ecd2d5367ca936cf6fc6ec8168c2b360d0/source/blender/draw/engines/workbench/shaders/workbench_matcap_lib.glsl), and it creates an orthonormal basis from the Incoming vector, then projects the view normal on to the axes.
But I'm not sure if it makes sense to generate an orthonormal basis in projection space. (???)

I tried to mimic that approach and if I generate a second axis with Gram–Schmidt and then a third one based on the cross product from the previous ones I get a similar result, where you get rings in one axis and "reflections" in the other.
But if I generate both axis I get rings on both.

```glsl
vec3 screen_normal_3(vec3 normal)
{
	vec3 view_normal   = transform_normal(CAMERA, normal);
	vec3 view_incoming = transform_normal(CAMERA, view_direction());
	
	vec3 right = vec3(1,0,0);
	vec3 tangent = normalize(right - view_incoming * dot(right, view_incoming));
	vec3 up = vec3(0,1,0);
	vec3 bitangent = normalize(up - view_incoming * dot(up, view_incoming));

	vec3 result = vec3
	(
		dot(view_normal, _tangent),
		dot(view_normal, _bitangent),
		dot(view_normal, view_incoming)
	);

	result = normalize(result);

	result.xy = result.xy * 0.496 + 0.5;
	return result;
}
```
Here you can see how horizontal planes look the same as in the workbench engine:
Worbench:
![workbench](https://user-images.githubusercontent.com/36610999/104859188-a90f1f00-5923-11eb-99cb-ab743aa5e9c8.png)
Example:
![malt](https://user-images.githubusercontent.com/36610999/104859190-aad8e280-5923-11eb-8beb-069a6c722b95.png)

I think the real problem here is that matcaps don't really make any sense in perspective, so you enter a "pick your poison" situation.
Maybe it would make more sense to provide one matcap mapping option for diffuse matcaps and another one for reflections?

**Comment by ConstaChugga** [comment]
> May I ask where the math from your code comes from?

Both the source for the [GoldSrc model viewer utility](https://github.com/ValveSoftware/halflife/blob/master/utils/mdlviewer/studio_render.cpp#L441-L475), and [this blog post that is entirely in chinese](https://zhuanlan.zhihu.com/p/59658622), save for the code. Although, I didn't actually wind up using the model viewer stuff, as it (and the goldSrc engine) calculate the incoming view vector per-bone rather (I also just realized it's probably not necessary to translate the incoming and normal vectors into view space).

I could've sworn I got that tree-ring problem to occur in workbench (though I might've just been an idiot and still in material view with the bogus shader) but I cannot get it to happen nary in eevee or workbench now. It's not straight for sure but it's not that horrible tree-ring.

![treeringWorkbech](https://user-images.githubusercontent.com/22027276/104903014-b5ec3c80-593c-11eb-8aa8-d0a12ce6ddd4.png)


I wasn't actually intending to solve the rings problem btw, I didn't know about it. I was trying to fix the issue where near the screen edges the chrome looks silk-screen'd onto the model rather than still facing the view like a sprite (as seen in the blog post). 
![image](https://user-images.githubusercontent.com/22027276/104900494-58a2bc00-5939-11eb-98d5-4a30ae5d807f.png)

**Comment by pragma37** [comment]
I may try something fancier in the future, but for now I updated the repo with the code I posted above. 
c4b8d7e3e7bdaec15501c6de63325037a8a3c812
(After fixing it, it had an error, the screenshot above doesn't match the current behaviour)

Please, take a look at it first, but I think we can close this issue now.

**Comment by ConstaChugga** [comment]
1. Yours works correctly. Sick
2. Looking at the differences between the two (mine is the red channel, yours is the green) shows no massive differences between them, other than yours having less bending towards the corners of the screen on flat surfaces. That's goode I'd say 👍 
![diffo](https://user-images.githubusercontent.com/22027276/104969330-64c46300-59a5-11eb-8a56-365e70d945ec.png)

**Comment by pragma37** [comment]
Nice, closing then.
