### ISSUE TITLE
F12 render blinks, then dissapears

### ISSUE THREAD

**Issue by tonpix** [bnpr/Malt#60]
Clip: https://streamable.com/yj0q9i

Basically started rendering, takes some seconds to render, render appears for like 0.5s and dissapears. Not sure if I'm missing something. (happens in 0:29s timestamp of clip)

Blender 2.9.2, it happens on both yesterday's and today's builds (beta + refactor)

**Comment by pragma37** [comment]
I need more info. https://github.com/bnpr/Malt#bug-reports

**Comment by tonpix** [comment]
> I need more info. https://github.com/bnpr/Malt#bug-reports

There https://drive.google.com/file/d/1bAuDSxqQoYKSmypCj1BxG3Yu6uryMCoO/view?usp=sharing

Open .blend, make sure camera view is enabled, press F12

**Comment by pragma37** [comment]
You have compositing enabled but the render is not connected to the  output.

![image](https://user-images.githubusercontent.com/36610999/109016184-2f9ee500-76b6-11eb-97af-83c456e75160.png)

EEVEE shows the exact same behaviour, please double check that your issue is related to Malt before submiting it.
